# Generated by Django 4.1 on 2022-08-30 10:53

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=100)),
                ('otasining_ismi', models.CharField(max_length=100)),
                ('ishga_kirgan_vaqti', models.DateField()),
                ('tugilgan_yili', models.DateField()),
                ('millati', model_utils.fields.StatusField(choices=[('Uzbek', 'Uzbek'), ('Qozoq', 'Qozoq'), ('Rus', 'Rus'), ('Tojik', 'Tojik')], default='Uzbek', max_length=100, no_check_for_status=True)),
                ('malumoti', models.CharField(max_length=100)),
                ('mutaxasisligi', models.CharField(max_length=300)),
                ('chet_tili', models.CharField(max_length=100)),
                ('davlat_mukofati', model_utils.fields.StatusField(choices=[('ha', 'ha'), ("yo'q", "yo'q")], default='ha', max_length=100, no_check_for_status=True)),
                ('deputatmi', model_utils.fields.StatusField(choices=[('ha', 'ha'), ("yo'q", "yo'q")], default='ha', max_length=100, no_check_for_status=True)),
                ('t_joyi', models.CharField(max_length=100)),
                ('partiyaviyligi', models.CharField(max_length=100)),
                ('tamomlagan_joyi', models.CharField(max_length=100)),
                ('ilmiy_unvoni', models.CharField(max_length=100)),
                ('harbiy_unvoni', models.CharField(max_length=100)),
                ('mehnat_faoliyati', models.TextField()),
                ('img', models.ImageField(upload_to='user/')),
            ],
        ),
    ]
