# Generated by Django 4.1 on 2022-09-02 04:01

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('javapdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mehnat_faoliyati',
            field=django_quill.fields.QuillField(),
        ),
    ]
