# Generated by Django 4.1 on 2022-09-04 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('javapdf', '0002_alter_employee_mehnat_faoliyati'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='mehnat_faoliyati',
            new_name='content',
        ),
    ]
